# Setup
title: Alvar Hansen
tagline: iOS Developer notes from Estonia
avatar: https://avatars.githubusercontent.com/u/482293?s=480&v=4
url: https://blog.hansen.ee
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-HY8SV5RYH9

# Specify the author for blog posts
author:
  name: Alvar Hansen
  url: https://twitter.com/allu22
  email: alvar@hansen.ee

# Custom vars
version: 3.0.0
